# Generated by Django 6.0.7 on 2026-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('found', 'Found'), ('returned', 'Returned')], default='found', max_length=20),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('possible_match', 'Possible Match'), ('recovered', 'Recovered')], default='lost', max_length=20),
        ),
    ]
